In [1]:
import pandas as pd

from src.config.settings import RAW_PATH

In [2]:
raw_files = list(RAW_PATH.glob("*.parquet"))

raw_files

[WindowsPath('C:/Users/Melc/Desktop/Proiect_Bosch/data_storage/raw/doe_alternative_fuel_stations.parquet'),
 WindowsPath('C:/Users/Melc/Desktop/Proiect_Bosch/data_storage/raw/epa_vehicle_fuel_economy.parquet'),
 WindowsPath('C:/Users/Melc/Desktop/Proiect_Bosch/data_storage/raw/nhtsa_vehicle_complaints.parquet')]

In [ ]:

nhtsa = pd.read_parquet(
    RAW_PATH / "nhtsa_vehicle_complaints.parquet"
)

nhtsa.head()

,1633421\t11292384\tHonda (American Honda Motor Co.)\tHONDA\tACCORD\t2018\tN\t20191221\tN\t0\t0\tSERVICE BRAKES\tPHILADELPHIA\tPA\t1HGCV2F38JA\t20200101\t20200101\t4\t\tDRIVING AT THE HIGHWAY,CAR SUDDENLY SLOW DOWN FROM 70MPH TO 40-50MPH,THERE WERE ANY CAR IN FRONT OF ME! I HAVE NOTHING ON MY WINDSHIELD! THERE WEREN'T ANY STOP OR TRAFFIC SIGN! SO HONDA STOP SAYING I AM DRIVING RECKLESSLY! FOR FEW SECOND I REGAINED CONTROL OF GAS,I HAVE TO SPEED UP MY CAR SO I DON'T GET REAR END,THEN EVERYTHING HAPPEN AGAIN,CAR DECIDED TO TAP BRAKE BY ITSELF. THIS HAPPEN MULTIPLE TIME DURING THE HIGHWAY DRIVING. SCREEN POP UP SAID COLLISION MITIGATION BREAK SYSTEM ERROR. PLEASE CONTACT HONDA DEALERSHIP. AFTER CONTACT DEALERSHIP FOR REPAIR. WAS TOLD THAT THEY COULD NOT DETERMINED THE PROBLEM SINCE THE ERROR DID NOT SHOW UP DURING THEIR IN HOUSE TESTING. AND YES,ERROR CODE DISAPPEARED AFTER CAR RESTARTED. BUT PROBLEM CONSISTS AFTER LONG DISTANCE DRIVE. I DON'T KNOW I SHOULD DRIVE THIS CAR OR I HAVE PRAY YOU GOD THAT ONE DAY I DON'T GET REAR END BECAUSE HONDA ACCORD DECIDES TO BRAKE ITSELF!\tIVOQ\tN\t\tN\tN\tN\t\t\t\t\t\t68\t\t\t\t\t\t\t\t\t\t\t\t\t\tV\t\tN\tN\t\t
0,1633422\t11292384\tHonda (American Honda Motor...,CAR SUDDENLY SLOW DOWN FROM 70MPH TO 40-50MPH,THERE WERE ANY CAR IN FRONT OF ME! I HAVE NOTH...,I HAVE TO SPEED UP MY CAR SO I DON'T GET REAR...,THEN EVERYTHING HAPPEN AGAIN,CAR DECIDED TO TAP BRAKE BY ITSELF. THIS HAPP...,ERROR CODE DISAPPEARED AFTER CAR RESTARTED. B...
1,1633423\t11292384\tHonda (American Honda Motor...,CAR SUDDENLY SLOW DOWN FROM 70MPH TO 40-50MPH,THERE WERE ANY CAR IN FRONT OF ME! I HAVE NOTH...,I HAVE TO SPEED UP MY CAR SO I DON'T GET REAR...,THEN EVERYTHING HAPPEN AGAIN,CAR DECIDED TO TAP BRAKE BY ITSELF. THIS HAPP...,ERROR CODE DISAPPEARED AFTER CAR RESTARTED. B...
2,1633424\t11292385\tFord Motor Company\tFORD\tE...,None,None,None,None,None,None
3,1633425\t11292386\tGeneral Motors,LLC\tCHEVROLET\tVOLT\t2017\tN\t20190712\tN\t0...,THE ADAPTIVE CRUISE CONTROL WILL NOT ENGAGE 2...,THIS CREATES A SAFETY HAZARD AS YOU NEVER KNO...,None,None,None
4,1633426\t11292386\tGeneral Motors,LLC\tCHEVROLET\tVOLT\t2017\tN\t20190712\tN\t0...,THE ADAPTIVE CRUISE CONTROL WILL NOT ENGAGE 2...,THIS CREATES A SAFETY HAZARD AS YOU NEVER KNO...,None,None,None

In [4]:
nhtsa.columns.tolist()

['1633421\t11292384\tHonda (American Honda Motor Co.)\tHONDA\tACCORD\t2018\tN\t20191221\tN\t0\t0\tSERVICE BRAKES\tPHILADELPHIA\tPA\t1HGCV2F38JA\t20200101\t20200101\t4\t\tDRIVING AT THE HIGHWAY',
 ' CAR SUDDENLY SLOW DOWN FROM 70MPH TO 40-50MPH',
 "THERE WERE ANY CAR IN FRONT OF ME! I HAVE NOTHING ON MY WINDSHIELD! THERE WEREN'T ANY STOP OR TRAFFIC SIGN! SO HONDA STOP SAYING I AM DRIVING RECKLESSLY!  FOR FEW SECOND I REGAINED CONTROL OF GAS",
 " I HAVE TO SPEED UP MY CAR SO I DON'T GET REAR END",
 ' THEN EVERYTHING HAPPEN AGAIN',
 ' CAR DECIDED TO TAP BRAKE BY ITSELF. THIS HAPPEN MULTIPLE TIME DURING THE HIGHWAY DRIVING. SCREEN POP UP SAID COLLISION MITIGATION BREAK SYSTEM ERROR. PLEASE CONTACT HONDA DEALERSHIP. AFTER CONTACT DEALERSHIP FOR REPAIR. WAS TOLD THAT THEY COULD NOT DETERMINED THE PROBLEM SINCE THE ERROR DID NOT SHOW UP DURING THEIR IN HOUSE TESTING. AND YES',
 " ERROR CODE DISAPPEARED AFTER CAR RESTARTED. BUT PROBLEM CONSISTS AFTER LONG DISTANCE DRIVE. I DON'T KNOW I SHOULD DRIVE THIS CAR OR I HAVE PRAY YOU GOD THAT ONE DAY I DON'T GET REAR END BECAUSE HONDA ACCORD DECIDES TO BRAKE ITSELF!\tIVOQ\tN\t\tN\tN\tN\t\t\t\t\t\t68\t\t\t\t\t\t\t\t\t\t\t\t\t\tV\t\tN\tN\t\t"]

In [6]:
nhtsa.info(verbose=True)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 350694 entries, 0 to 350693
Data columns (total 7 columns):
 #   Column                                                                                                                                                                                                                                                                                                                                                   Non-Null Count   Dtype
---  ------                                                                                                                                                                                                                                                                                                                                                   --------------   -----
 0   1633421	11292384	Honda (American Honda Motor Co.)	HONDA	ACCORD	2018	N	20191221	N	0	0	SERVICE BRAKES	PHILADELPHIA	PA	1HGCV2F38JA	20200101	20200101	4		DRIVING AT THE HIGHWAY                                                                                                                                                                              350694 non-null  object
 1    CAR SUDDENLY SLOW DOWN FROM 70MPH TO 40-50MPH                                                                                                                                                                                                                                                                                                           303873 non-null  object
 2   THERE WERE ANY CAR IN FRONT OF ME! I HAVE NOTHING ON MY WINDSHIELD! THERE WEREN'T ANY STOP OR TRAFFIC SIGN! SO HONDA STOP SAYING I AM DRIVING RECKLESSLY!  FOR FEW SECOND I REGAINED CONTROL OF GAS                                                                                                                                                      206265 non-null  object
 3    I HAVE TO SPEED UP MY CAR SO I DON'T GET REAR END                                                                                                                                                                                                                                                                                                       143709 non-null  object
 4    THEN EVERYTHING HAPPEN AGAIN                                                                                                                                                                                                                                                                                                                            92322 non-null   object
 5    CAR DECIDED TO TAP BRAKE BY ITSELF. THIS HAPPEN MULTIPLE TIME DURING THE HIGHWAY DRIVING. SCREEN POP UP SAID COLLISION MITIGATION BREAK SYSTEM ERROR. PLEASE CONTACT HONDA DEALERSHIP. AFTER CONTACT DEALERSHIP FOR REPAIR. WAS TOLD THAT THEY COULD NOT DETERMINED THE PROBLEM SINCE THE ERROR DID NOT SHOW UP DURING THEIR IN HOUSE TESTING. AND YES  52590 non-null   object
 6    ERROR CODE DISAPPEARED AFTER CAR RESTARTED. BUT PROBLEM CONSISTS AFTER LONG DISTANCE DRIVE. I DON'T KNOW I SHOULD DRIVE THIS CAR OR I HAVE PRAY YOU GOD THAT ONE DAY I DON'T GET REAR END BECAUSE HONDA ACCORD DECIDES TO BRAKE ITSELF!	IVOQ	N		N	N	N						68														V		N	N		                                                                     22452 non-null   object
dtypes: object(7)
memory usage: 18.7+ MB

In [7]:
doe = pd.read_parquet(
    RAW_PATH / "doe_alternative_fuel_stations.parquet"
)

doe.head()

,access_code,access_days_time,access_detail_code,cards_accepted,date_last_confirmed,expected_date,fuel_type_code,groups_with_access_code,id,maximum_vehicle_class,...,intersection_directions_fr,bd_blends_fr,groups_with_access_code_fr,ev_pricing_fr,ev_charging_units,federal_agency.id,federal_agency.code,federal_agency.name,ev_network_ids.station,ev_network_ids.posts
0,private,None,None,None,2026-06-12,None,CNG,Private,17,MD,...,None,None,Privé,None,None,NaN,None,None,None,None
1,private,None,GOVERNMENT,None,2024-02-12,None,CNG,Private - Government only,45,LD,...,None,None,Privé - Réservé au gouvernement,None,None,NaN,None,None,None,None
2,public,24 hours daily,CREDIT_CARD_ALWAYS,CREDIT M V Voyager,2025-06-06,None,CNG,Public - Credit card at all times,73,MD,...,None,None,Public - Carte de crédit en tout temps,None,None,NaN,None,None,None,None
3,public,24 hours daily; call 866-809-4869 for Clean En...,CREDIT_CARD_ALWAYS,A CleanEnergy Comdata D FuelMan M V Voyager Wr...,2025-09-12,None,CNG,Public - Credit card at all times,81,MD,...,None,None,Public - Carte de crédit en tout temps,None,None,NaN,None,None,None,None
4,public,24 hours daily; call 866-809-4869 for Clean En...,CREDIT_CARD_ALWAYS,CleanEnergy D FleetOne FuelMan M V Voyager Wri...,2025-09-12,None,CNG,Public - Credit card at all times,84,HD,...,None,None,Public - Carte de crédit en tout temps,None,None,NaN,None,None,None,None

In [8]:
doe.columns.tolist()

['access_code',
 'access_days_time',
 'access_detail_code',
 'cards_accepted',
 'date_last_confirmed',
 'expected_date',
 'fuel_type_code',
 'groups_with_access_code',
 'id',
 'maximum_vehicle_class',
 'open_date',
 'owner_type_code',
 'related_stations',
 'restricted_access',
 'status_code',
 'funding_sources',
 'facility_type',
 'station_name',
 'station_phone',
 'updated_at',
 'geocode_status',
 'latitude',
 'longitude',
 'city',
 'country',
 'intersection_directions',
 'plus4',
 'state',
 'street_address',
 'zip',
 'bd_blends',
 'cng_dispenser_num',
 'cng_fill_type_code',
 'cng_has_rng',
 'cng_psi',
 'cng_renewable_source',
 'cng_total_compression',
 'cng_total_storage',
 'cng_vehicle_class',
 'e85_blender_pump',
 'e85_other_ethanol_blends',
 'ev_connector_types',
 'ev_dc_fast_num',
 'ev_level1_evse_num',
 'ev_level2_evse_num',
 'ev_network',
 'ev_network_web',
 'ev_other_evse',
 'ev_pricing',
 'ev_renewable_source',
 'ev_workplace_charging',
 'hy_is_retail',
 'hy_pressures',
 'hy_standards',
 'hy_status_link',
 'lng_has_rng',
 'lng_renewable_source',
 'lng_vehicle_class',
 'lpg_nozzle_types',
 'lpg_primary',
 'ng_fill_type_code',
 'ng_psi',
 'ng_vehicle_class',
 'rd_blended_with_biodiesel',
 'rd_blends',
 'rd_blends_fr',
 'rd_max_biodiesel_level',
 'nps_unit_name',
 'access_days_time_fr',
 'intersection_directions_fr',
 'bd_blends_fr',
 'groups_with_access_code_fr',
 'ev_pricing_fr',
 'ev_charging_units',
 'federal_agency.id',
 'federal_agency.code',
 'federal_agency.name',
 'ev_network_ids.station',
 'ev_network_ids.posts']

In [10]:
doe.info(verbose=True)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 99412 entries, 0 to 99411
Data columns (total 79 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   access_code                 99412 non-null  object
 1   access_days_time            88282 non-null  object
 2   access_detail_code          9234 non-null   object
 3   cards_accepted              20990 non-null  object
 4   date_last_confirmed         99110 non-null  object
 5   expected_date               0 non-null      object
 6   fuel_type_code              99412 non-null  object
 7   groups_with_access_code     99412 non-null  object
 8   id                          99412 non-null  int64
 9   maximum_vehicle_class       27354 non-null  object
 10  open_date                   99098 non-null  object
 11  owner_type_code             36436 non-null  object
 12  related_stations            99412 non-null  object
 13  restricted_access           86470 non-null  object
 14  status_code                 99412 non-null  object
 15  funding_sources             242 non-null    object
 16  facility_type               35525 non-null  object
 17  station_name                99412 non-null  object
 18  station_phone               91911 non-null  object
 19  updated_at                  99412 non-null  object
 20  geocode_status              99408 non-null  object
 21  latitude                    99412 non-null  float64
 22  longitude                   99412 non-null  float64
 23  city                        99412 non-null  object
 24  country                     99412 non-null  object
 25  intersection_directions     27375 non-null  object
 26  plus4                       0 non-null      object
 27  state                       99412 non-null  object
 28  street_address              99365 non-null  object
 29  zip                         99412 non-null  object
 30  bd_blends                   2310 non-null   object
 31  cng_dispenser_num           1307 non-null   float64
 32  cng_fill_type_code          1337 non-null   object
 33  cng_has_rng                 1190 non-null   object
 34  cng_psi                     1322 non-null   object
 35  cng_renewable_source        859 non-null    object
 36  cng_total_compression       552 non-null    float64
 37  cng_total_storage           229 non-null    float64
 38  cng_vehicle_class           1385 non-null   object
 39  e85_blender_pump            5230 non-null   object
 40  e85_other_ethanol_blends    2312 non-null   object
 41  ev_connector_types          86088 non-null  object
 42  ev_dc_fast_num              15353 non-null  float64
 43  ev_level1_evse_num          674 non-null    float64
 44  ev_level2_evse_num          71873 non-null  float64
 45  ev_network                  86091 non-null  object
 46  ev_network_web              77308 non-null  object
 47  ev_other_evse               10 non-null     object
 48  ev_pricing                  9940 non-null   object
 49  ev_renewable_source         445 non-null    object
 50  ev_workplace_charging       86090 non-null  object
 51  hy_is_retail                53 non-null     object
 52  hy_pressures                60 non-null     object
 53  hy_standards                57 non-null     object
 54  hy_status_link              45 non-null     object
 55  lng_has_rng                 48 non-null     object
 56  lng_renewable_source        26 non-null     object
 57  lng_vehicle_class           63 non-null     object
 58  lpg_nozzle_types            2813 non-null   object
 59  lpg_primary                 2619 non-null   object
 60  ng_fill_type_code           1337 non-null   object
 61  ng_psi                      1322 non-null   object
 62  ng_vehicle_class            1448 non-null   object
 63  rd_blended_with_biodiesel   1119 non-null   object
 64  rd_blends                   1261 non-null   object
 65  rd_blends_fr                0 non-null      object
 66  rd_max_biodiesel_level      1065 non-null   object
 67  nps_unit_name               190 non-null    object
 68  access_days_time_fr         37 non-null     object
 69  intersection_directions_fr  0 non-null      object
 70  bd_blends_fr                0 non-null      object
 71  groups_with_access_code_fr  99412 non-null  object
 72  ev_pricing_fr               0 non-null      object
 73  ev_charging_units           86091 non-null  object
 74  federal_agency.id           2178 non-null   float64
 75  federal_agency.code         2178 non-null   object
 76  federal_agency.name         2178 non-null   object
 77  ev_network_ids.station      62966 non-null  object
 78  ev_network_ids.posts        62970 non-null  object
dtypes: float64(9), int64(1), object(69)
memory usage: 59.9+ MB

In [11]:
epa = pd.read_parquet(
    RAW_PATH / "epa_vehicle_fuel_economy.parquet"
)

epa.head()

,barrels08,barrelsA08,charge120,charge240,city08,city08U,cityA08,cityA08U,cityCD,cityE,...,mfrCode,c240Dscr,charge240b,c240bDscr,createdOn,modifiedOn,startStop,phevCity,phevHwy,phevComb
0,14.167143,0.0,0.0,0.0,19,0.0,0,0.0,0.0,0.0,...,None,None,0.0,None,Tue Jan 01 00:00:00 EST 2013,Tue Jan 01 00:00:00 EST 2013,None,0,0,0
1,27.046364,0.0,0.0,0.0,9,0.0,0,0.0,0.0,0.0,...,None,None,0.0,None,Tue Jan 01 00:00:00 EST 2013,Tue Jan 01 00:00:00 EST 2013,None,0,0,0
2,11.018889,0.0,0.0,0.0,23,0.0,0,0.0,0.0,0.0,...,None,None,0.0,None,Tue Jan 01 00:00:00 EST 2013,Tue Jan 01 00:00:00 EST 2013,None,0,0,0
3,27.046364,0.0,0.0,0.0,10,0.0,0,0.0,0.0,0.0,...,None,None,0.0,None,Tue Jan 01 00:00:00 EST 2013,Tue Jan 01 00:00:00 EST 2013,None,0,0,0
4,15.658421,0.0,0.0,0.0,17,0.0,0,0.0,0.0,0.0,...,None,None,0.0,None,Tue Jan 01 00:00:00 EST 2013,Tue Jan 01 00:00:00 EST 2013,None,0,0,0

In [12]:
epa.columns.tolist()

['barrels08',
 'barrelsA08',
 'charge120',
 'charge240',
 'city08',
 'city08U',
 'cityA08',
 'cityA08U',
 'cityCD',
 'cityE',
 'cityUF',
 'co2',
 'co2A',
 'co2TailpipeAGpm',
 'co2TailpipeGpm',
 'comb08',
 'comb08U',
 'combA08',
 'combA08U',
 'combE',
 'combinedCD',
 'combinedUF',
 'cylinders',
 'displ',
 'drive',
 'engId',
 'eng_dscr',
 'feScore',
 'fuelCost08',
 'fuelCostA08',
 'fuelType',
 'fuelType1',
 'ghgScore',
 'ghgScoreA',
 'highway08',
 'highway08U',
 'highwayA08',
 'highwayA08U',
 'highwayCD',
 'highwayE',
 'highwayUF',
 'hlv',
 'hpv',
 'id',
 'lv2',
 'lv4',
 'make',
 'model',
 'mpgData',
 'phevBlended',
 'pv2',
 'pv4',
 'range',
 'rangeCity',
 'rangeCityA',
 'rangeHwy',
 'rangeHwyA',
 'trany',
 'UCity',
 'UCityA',
 'UHighway',
 'UHighwayA',
 'VClass',
 'year',
 'youSaveSpend',
 'baseModel',
 'guzzler',
 'trans_dscr',
 'tCharger',
 'sCharger',
 'atvType',
 'fuelType2',
 'rangeA',
 'evMotor',
 'mfrCode',
 'c240Dscr',
 'charge240b',
 'c240bDscr',
 'createdOn',
 'modifiedOn',
 'startStop',
 'phevCity',
 'phevHwy',
 'phevComb']

In [13]:
epa.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 49927 entries, 0 to 49926
Data columns (total 84 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   barrels08        49927 non-null  float64
 1   barrelsA08       49927 non-null  float64
 2   charge120        49927 non-null  float64
 3   charge240        49927 non-null  float64
 4   city08           49927 non-null  int64
 5   city08U          49927 non-null  float64
 6   cityA08          49927 non-null  int64
 7   cityA08U         49927 non-null  float64
 8   cityCD           49927 non-null  float64
 9   cityE            49927 non-null  float64
 10  cityUF           49927 non-null  float64
 11  co2              49927 non-null  int64
 12  co2A             49927 non-null  int64
 13  co2TailpipeAGpm  49927 non-null  float64
 14  co2TailpipeGpm   49927 non-null  float64
 15  comb08           49927 non-null  int64
 16  comb08U          49927 non-null  float64
 17  combA08          49927 non-null  int64
 18  combA08U         49927 non-null  float64
 19  combE            49927 non-null  float64
 20  combinedCD       49927 non-null  float64
 21  combinedUF       49927 non-null  float64
 22  cylinders        48423 non-null  float64
 23  displ            48425 non-null  float64
 24  drive            48741 non-null  object
 25  engId            49927 non-null  int64
 26  eng_dscr         31679 non-null  object
 27  feScore          49927 non-null  int64
 28  fuelCost08       49927 non-null  int64
 29  fuelCostA08      49927 non-null  int64
 30  fuelType         49927 non-null  object
 31  fuelType1        49925 non-null  object
 32  ghgScore         49927 non-null  int64
 33  ghgScoreA        49927 non-null  int64
 34  highway08        49927 non-null  int64
 35  highway08U       49927 non-null  float64
 36  highwayA08       49927 non-null  int64
 37  highwayA08U      49927 non-null  float64
 38  highwayCD        49927 non-null  float64
 39  highwayE         49927 non-null  float64
 40  highwayUF        49927 non-null  float64
 41  hlv              49927 non-null  int64
 42  hpv              49927 non-null  int64
 43  id               49927 non-null  int64
 44  lv2              49927 non-null  int64
 45  lv4              49927 non-null  int64
 46  make             49927 non-null  object
 47  model            49927 non-null  object
 48  mpgData          49846 non-null  object
 49  phevBlended      49927 non-null  bool
 50  pv2              49927 non-null  int64
 51  pv4              49927 non-null  int64
 52  range            49927 non-null  int64
 53  rangeCity        49927 non-null  float64
 54  rangeCityA       49927 non-null  float64
 55  rangeHwy         49927 non-null  float64
 56  rangeHwyA        49927 non-null  float64
 57  trany            49916 non-null  object
 58  UCity            49927 non-null  float64
 59  UCityA           49927 non-null  float64
 60  UHighway         49927 non-null  float64
 61  UHighwayA        49927 non-null  float64
 62  VClass           49927 non-null  object
 63  year             49927 non-null  int64
 64  youSaveSpend     49927 non-null  int64
 65  baseModel        49927 non-null  object
 66  guzzler          2838 non-null   object
 67  trans_dscr       15044 non-null  object
 68  tCharger         11573 non-null  object
 69  sCharger         1144 non-null   object
 70  atvType          6602 non-null   object
 71  fuelType2        2008 non-null   object
 72  rangeA           2005 non-null   object
 73  evMotor          3480 non-null   object
 74  mfrCode          19119 non-null  object
 75  c240Dscr         141 non-null    object
 76  charge240b       49927 non-null  float64
 77  c240bDscr        135 non-null    object
 78  createdOn        49927 non-null  object
 79  modifiedOn       49927 non-null  object
 80  startStop        18238 non-null  object
 81  phevCity         49927 non-null  int64
 82  phevHwy          49927 non-null  int64
 83  phevComb         49927 non-null  int64
dtypes: bool(1), float64(32), int64(27), object(24)
memory usage: 31.7+ MB

In [14]:
import zipfile
import requests
from io import BytesIO

url = "https://static.nhtsa.gov/odi/ffdd/cmpl/COMPLAINTS_RECEIVED_2020-2024.zip"

response = requests.get(url)

zip_file = zipfile.ZipFile(
    BytesIO(response.content)
)

zip_file.namelist()

['COMPLAINTS_RECEIVED_2020-2024.txt']

In [15]:
file_name = zip_file.namelist()[0]

print(file_name)

COMPLAINTS_RECEIVED_2020-2024.txt

In [16]:
with zip_file.open(file_name) as f:

    for i in range(10):
        print(f.readline())

b"1633421\t11292384\tHonda (American Honda Motor Co.)\tHONDA\tACCORD\t2018\tN\t20191221\tN\t0\t0\tSERVICE BRAKES\tPHILADELPHIA\tPA\t1HGCV2F38JA\t20200101\t20200101\t4\t\tDRIVING AT THE HIGHWAY, CAR SUDDENLY SLOW DOWN FROM 70MPH TO 40-50MPH,THERE WERE ANY CAR IN FRONT OF ME! I HAVE NOTHING ON MY WINDSHIELD! THERE WEREN'T ANY STOP OR TRAFFIC SIGN! SO HONDA STOP SAYING I AM DRIVING RECKLESSLY!  FOR FEW SECOND I REGAINED CONTROL OF GAS, I HAVE TO SPEED UP MY CAR SO I DON'T GET REAR END, THEN EVERYTHING HAPPEN AGAIN, CAR DECIDED TO TAP BRAKE BY ITSELF. THIS HAPPEN MULTIPLE TIME DURING THE HIGHWAY DRIVING. SCREEN POP UP SAID COLLISION MITIGATION BREAK SYSTEM ERROR. PLEASE CONTACT HONDA DEALERSHIP. AFTER CONTACT DEALERSHIP FOR REPAIR. WAS TOLD THAT THEY COULD NOT DETERMINED THE PROBLEM SINCE THE ERROR DID NOT SHOW UP DURING THEIR IN HOUSE TESTING. AND YES, ERROR CODE DISAPPEARED AFTER CAR RESTARTED. BUT PROBLEM CONSISTS AFTER LONG DISTANCE DRIVE. I DON'T KNOW I SHOULD DRIVE THIS CAR OR I HAVE PRAY YOU GOD THAT ONE DAY I DON'T GET REAR END BECAUSE HONDA ACCORD DECIDES TO BRAKE ITSELF!\tIVOQ\tN\t\tN\tN\tN\t\t\t\t\t\t68\t\t\t\t\t\t\t\t\t\t\t\t\t\tV\t\tN\tN\t\t\n"
b"1633422\t11292384\tHonda (American Honda Motor Co.)\tHONDA\tACCORD\t2018\tN\t20191221\tN\t0\t0\tELECTRICAL SYSTEM\tPHILADELPHIA\tPA\t1HGCV2F38JA\t20200101\t20200101\t4\t\tDRIVING AT THE HIGHWAY, CAR SUDDENLY SLOW DOWN FROM 70MPH TO 40-50MPH,THERE WERE ANY CAR IN FRONT OF ME! I HAVE NOTHING ON MY WINDSHIELD! THERE WEREN'T ANY STOP OR TRAFFIC SIGN! SO HONDA STOP SAYING I AM DRIVING RECKLESSLY!  FOR FEW SECOND I REGAINED CONTROL OF GAS, I HAVE TO SPEED UP MY CAR SO I DON'T GET REAR END, THEN EVERYTHING HAPPEN AGAIN, CAR DECIDED TO TAP BRAKE BY ITSELF. THIS HAPPEN MULTIPLE TIME DURING THE HIGHWAY DRIVING. SCREEN POP UP SAID COLLISION MITIGATION BREAK SYSTEM ERROR. PLEASE CONTACT HONDA DEALERSHIP. AFTER CONTACT DEALERSHIP FOR REPAIR. WAS TOLD THAT THEY COULD NOT DETERMINED THE PROBLEM SINCE THE ERROR DID NOT SHOW UP DURING THEIR IN HOUSE TESTING. AND YES, ERROR CODE DISAPPEARED AFTER CAR RESTARTED. BUT PROBLEM CONSISTS AFTER LONG DISTANCE DRIVE. I DON'T KNOW I SHOULD DRIVE THIS CAR OR I HAVE PRAY YOU GOD THAT ONE DAY I DON'T GET REAR END BECAUSE HONDA ACCORD DECIDES TO BRAKE ITSELF!\tIVOQ\tN\t\tN\tN\tN\t\t\t\t\t\t68\t\t\t\t\t\t\t\t\t\t\t\t\t\tV\t\tN\tN\t\t\n"
b"1633423\t11292384\tHonda (American Honda Motor Co.)\tHONDA\tACCORD\t2018\tN\t20191221\tN\t0\t0\tENGINE\tPHILADELPHIA\tPA\t1HGCV2F38JA\t20200101\t20200101\t4\t\tDRIVING AT THE HIGHWAY, CAR SUDDENLY SLOW DOWN FROM 70MPH TO 40-50MPH,THERE WERE ANY CAR IN FRONT OF ME! I HAVE NOTHING ON MY WINDSHIELD! THERE WEREN'T ANY STOP OR TRAFFIC SIGN! SO HONDA STOP SAYING I AM DRIVING RECKLESSLY!  FOR FEW SECOND I REGAINED CONTROL OF GAS, I HAVE TO SPEED UP MY CAR SO I DON'T GET REAR END, THEN EVERYTHING HAPPEN AGAIN, CAR DECIDED TO TAP BRAKE BY ITSELF. THIS HAPPEN MULTIPLE TIME DURING THE HIGHWAY DRIVING. SCREEN POP UP SAID COLLISION MITIGATION BREAK SYSTEM ERROR. PLEASE CONTACT HONDA DEALERSHIP. AFTER CONTACT DEALERSHIP FOR REPAIR. WAS TOLD THAT THEY COULD NOT DETERMINED THE PROBLEM SINCE THE ERROR DID NOT SHOW UP DURING THEIR IN HOUSE TESTING. AND YES, ERROR CODE DISAPPEARED AFTER CAR RESTARTED. BUT PROBLEM CONSISTS AFTER LONG DISTANCE DRIVE. I DON'T KNOW I SHOULD DRIVE THIS CAR OR I HAVE PRAY YOU GOD THAT ONE DAY I DON'T GET REAR END BECAUSE HONDA ACCORD DECIDES TO BRAKE ITSELF!\tIVOQ\tN\t\tN\tN\tN\t\t\t\t\t\t68\t\t\t\t\t\t\t\t\t\t\t\t\t\tV\t\tN\tN\t\t\n"
b'1633424\t11292385\tFord Motor Company\tFORD\tEXPLORER\t2020\tN\t20191226\tN\t0\t0\tELECTRICAL SYSTEM\tMEHERRIN\tVA\t1FM5K8GC8LG\t20200101\t20200101\t5300\t\tDEEP SLEEP MODE ACTIVATES AFTER 2 DAYS.  MOST RECENT EXPERIENCE INVOLVED HAVING TO JUMP START THE CAR AFTER SETTING 3 DAYS.\tIVOQ\tN\t\tN\tN\tN\t\t\t\t\t\t0\t\t\t\t\t\t\t\t\t\t\t\t\t\tV\t\tN\tN\t\t\n'
b'1633425\t11292386\tGeneral Motors, LLC\tCHEVROLET\tVOLT\t2017\tN\t20190712\tN\t0\t0\tSERVICE BRAKES\tSAN ANTONIO\tTX\t1G1RB6S52HU\t20200101\t20200101\t15000\t\tWHILE DRIVING ON CITY STREETS AND HIGHWAYS, THE ADAPTIVE CRUISE CONTROL WILL NOT ENGAGE 25% OF THE TIME AND WILL DISENGAGE WITHOUT NOTICE.  "ADAPTIVE CRUISE CONTROL WILL APPEAR IN DIC.  HOWEVER, THIS CREATES A SAFETY HAZARD AS YOU NEVER KNOW IF THE CAR WILL AUTOMATICALLY SLOW DOWN.  I HAVE FILED CASE # 9-5379585813 WITH CHEVROLET AND BEEN TO FOUR DEALERS AND THEY REFUSE TO FIX THE PROBLEM.  THEY NO LONGER RETURN MY CALLS.  I AM AFRAID TO USE THE CRUISE CONTROL.\tIVOQ\tN\t\tN\tN\tN\t\t\t\t\t\t70\t\t\t\t\t\t\t\t\t\t\t\t\t\tV\t\tN\tN\t\t\n'
b'1633426\t11292386\tGeneral Motors, LLC\tCHEVROLET\tVOLT\t2017\tN\t20190712\tN\t0\t0\tELECTRONIC STABILITY CONTROL (ESC)\tSAN ANTONIO\tTX\t1G1RB6S52HU\t20200101\t20200101\t15000\t\tWHILE DRIVING ON CITY STREETS AND HIGHWAYS, THE ADAPTIVE CRUISE CONTROL WILL NOT ENGAGE 25% OF THE TIME AND WILL DISENGAGE WITHOUT NOTICE.  "ADAPTIVE CRUISE CONTROL WILL APPEAR IN DIC.  HOWEVER, THIS CREATES A SAFETY HAZARD AS YOU NEVER KNOW IF THE CAR WILL AUTOMATICALLY SLOW DOWN.  I HAVE FILED CASE # 9-5379585813 WITH CHEVROLET AND BEEN TO FOUR DEALERS AND THEY REFUSE TO FIX THE PROBLEM.  THEY NO LONGER RETURN MY CALLS.  I AM AFRAID TO USE THE CRUISE CONTROL.\tIVOQ\tN\t\tN\tN\tN\t\t\t\t\t\t70\t\t\t\t\t\t\t\t\t\t\t\t\t\tV\t\tN\tN\t\t\n'
b'1633427\t11292386\tGeneral Motors, LLC\tCHEVROLET\tVOLT\t2017\tN\t20190712\tN\t0\t0\tVEHICLE SPEED CONTROL\tSAN ANTONIO\tTX\t1G1RB6S52HU\t20200101\t20200101\t15000\t\tWHILE DRIVING ON CITY STREETS AND HIGHWAYS, THE ADAPTIVE CRUISE CONTROL WILL NOT ENGAGE 25% OF THE TIME AND WILL DISENGAGE WITHOUT NOTICE.  "ADAPTIVE CRUISE CONTROL WILL APPEAR IN DIC.  HOWEVER, THIS CREATES A SAFETY HAZARD AS YOU NEVER KNOW IF THE CAR WILL AUTOMATICALLY SLOW DOWN.  I HAVE FILED CASE # 9-5379585813 WITH CHEVROLET AND BEEN TO FOUR DEALERS AND THEY REFUSE TO FIX THE PROBLEM.  THEY NO LONGER RETURN MY CALLS.  I AM AFRAID TO USE THE CRUISE CONTROL.\tIVOQ\tN\t\tN\tN\tN\t\t\t\t\t\t70\t\t\t\t\t\t\t\t\t\t\t\t\t\tV\t\tN\tN\t\t\n'
b"1633428\t11292387\tToyota Motor Corporation\tTOYOTA\tCAMRY\t2014\tN\t20160701\tN\t0\t0\tPOWER TRAIN\tCROFTON\tMD\t4T1BF1FK2EU\t20200101\t20200101\t\t\tWHEN I STEP ON THE GAS AT LOW SPEED, NORMALLY BETWEEN 30-50MPH MY CAR VIBRATES OR SHUDDERS. IT ONLY DOES THIS WHEN I'M TRYING TO MAINTAIN THOSE LOWER SPEEDS, SO THE PEDAL IS JUST BARELY BEING PRESSED DOWN. ONCE I'M ON THE HIGHWAY ABOVE 50MPH I DON'T HAVE ANY ISSUES.\tIVOQ\tN\t\tN\tN\tN\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\tV\t\tN\tN\t\t\n"
b"1633429\t11292388\tGeneral Motors, LLC\tCHEVROLET\tMALIBU\t2007\tN\t20191223\tN\t0\t0\tSTEERING\tSOUTH SAINT PAUL\tMN\t1G1ZS57N37F\t20200101\t20200101\t200000\t\tTHE POWER STEERING WILL OCCASIONALLY NOT WORK WHEN YOU START THE CAR BUT IF YOU TURN IT OFF AND START IT UP AGAIN IT WILL WORK. I'LL OCCASIONALLY GET A BURNING SMELL THROUGH MY VENTS AND MY STEERING WHEEL WILL PERIODICALLY SHAKE AS WELL.. I RECENTLY BOUT NEW TIRES OVER THE SUMMER AND IT STOPPED HAPPENING SO I THOUGHT NOTHING OF IT BUT AFTER WASHING MY CAR THE OTHER DAY IT STARTED DOING IT AGAIN\tIVOQ\tN\t\tN\tN\tN\t\t\t\t\t\t0\t\t\t\t\t\t\t\t\t\t\t\t\t\tV\t\tN\tN\t\t\n"
b'1633430\t11292389\tHyundai Motor America\tHYUNDAI\tAZERA\t2015\tN\t20200101\tN\t0\t0\tSERVICE BRAKES\tPELHAM\tAL\tKMHFH4JG0FA\t20200101\t20200101\t80000\t\tHIT A BUMP IN ROAD AND LOST CONTROL OF CAR. UNSTABLE BOUNCING ?IN MOTION\tIVOQ\tN\t\tN\tN\tN\t\t\t\t\t\t65\t\t\t\t\t\t\t\t\t\t\t\t\t\tV\t\tN\tN\t\t\n'